apiVersion: v2
name: hydrator-demo
description: A Helm chart for Kubernetes

version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 58.7.2
